// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::BluetoothProperties {

enum class snoop_default_mode_values {
    EMPTY,
    DISABLED,
    FILTERED,
    FULL,
};

std::optional<snoop_default_mode_values> snoop_default_mode();
bool snoop_default_mode(const std::optional<snoop_default_mode_values>& value);

enum class snoop_log_mode_values {
    EMPTY,
    DISABLED,
    FILTERED,
    FULL,
};

std::optional<snoop_log_mode_values> snoop_log_mode();
bool snoop_log_mode(const std::optional<snoop_log_mode_values>& value);

std::optional<bool> snoop_log_filter_snoop_headers_enabled();
bool snoop_log_filter_snoop_headers_enabled(const std::optional<bool>& value);

std::optional<bool> snoop_log_filter_profile_a2dp_enabled();
bool snoop_log_filter_profile_a2dp_enabled(const std::optional<bool>& value);

enum class snoop_log_filter_profile_map_values {
    EMPTY,
    DISABLED,
    FULLFILTER,
    HEADER,
    MAGIC,
};

std::optional<snoop_log_filter_profile_map_values> snoop_log_filter_profile_map();
bool snoop_log_filter_profile_map(const std::optional<snoop_log_filter_profile_map_values>& value);

enum class snoop_log_filter_profile_pbap_values {
    EMPTY,
    DISABLED,
    FULLFILTER,
    HEADER,
    MAGIC,
};

std::optional<snoop_log_filter_profile_pbap_values> snoop_log_filter_profile_pbap();
bool snoop_log_filter_profile_pbap(const std::optional<snoop_log_filter_profile_pbap_values>& value);

std::optional<bool> snoop_log_filter_profile_rfcomm_enabled();
bool snoop_log_filter_profile_rfcomm_enabled(const std::optional<bool>& value);

std::optional<bool> factory_reset();
bool factory_reset(const std::optional<bool>& value);

std::vector<std::optional<std::string>> le_audio_allow_list();
bool le_audio_allow_list(const std::vector<std::optional<std::string>>& value);

std::optional<bool> isGapLePrivacyEnabled();

std::optional<std::int32_t> getGapLeConnMinLimit();

std::optional<bool> isGapLeConnOnlyInit1mPhyEnabled();

std::optional<bool> isLeAudioInbandRingtoneSupported();

std::optional<std::string> getDefaultDeviceName();

std::vector<std::optional<std::uint32_t>> getClassOfDevice();

std::optional<std::int32_t> getDefaultOutputOnlyAudioProfile();

std::optional<std::int32_t> getDefaultDuplexAudioProfile();

std::optional<std::int32_t> getHardwareOperatingVoltageMv();

std::optional<std::int32_t> getHardwareIdleCurrentMa();

std::optional<std::int32_t> getHardwareTxCurrentMa();

std::optional<std::int32_t> getHardwareRxCurrentMa();

std::optional<bool> isSupportPersistedStateEnabled();

std::optional<bool> isAdapterAddressValidationEnabled();

std::optional<bool> isProfileA2dpSinkEnabled();

std::optional<bool> isProfileA2dpSourceEnabled();

std::optional<bool> isProfileAshaCentralEnabled();

std::optional<bool> isProfileAvrcpControllerEnabled();

std::optional<bool> isProfileAvrcpTargetEnabled();

std::optional<bool> isProfileBapBroadcastAssistEnabled();

std::optional<bool> isProfileBapBroadcastSourceEnabled();

std::optional<bool> isProfileBapUnicastClientEnabled();

std::optional<bool> isProfileBasClientEnabled();

std::optional<bool> isProfileBassClientEnabled();

std::optional<bool> isProfileCsipSetCoordinatorEnabled();

std::optional<bool> isProfileGattEnabled();

std::optional<bool> isProfileHapClientEnabled();

std::optional<bool> isProfileHfpAgEnabled();

std::optional<bool> isProfileHfpHfEnabled();

std::optional<bool> isProfileHidDeviceEnabled();

std::optional<bool> isProfileHidHostEnabled();

std::optional<bool> isProfileMapClientEnabled();

std::optional<bool> isProfileMapServerEnabled();

std::optional<bool> isProfileMcpServerEnabled();

std::optional<bool> isProfileOppEnabled();

std::optional<bool> isProfilePanNapEnabled();

std::optional<bool> isProfilePanPanuEnabled();

std::optional<bool> isProfilePbapClientEnabled();

std::optional<bool> isProfilePbapServerEnabled();

std::optional<bool> isProfilePbapSimEnabled();

std::optional<bool> isProfileSapServerEnabled();

std::optional<bool> isProfileCcpServerEnabled();

std::optional<bool> isProfileVcpControllerEnabled();

std::optional<std::uint32_t> getLinkSupervisionTimeout();

std::optional<std::uint32_t> getClassicPageScanType();

std::optional<std::uint32_t> getClassicPageScanInterval();

std::optional<std::uint32_t> getClassicPageScanWindow();

std::optional<std::uint32_t> getClassicInquiryScanType();

std::optional<std::uint32_t> getClassicInquiryScanInterval();

std::optional<std::uint32_t> getClassicInquiryScanWindow();

std::optional<std::uint32_t> getClassicPageTimeout();

std::vector<std::optional<std::uint32_t>> getClassicSniffMaxIntervals();

std::vector<std::optional<std::uint32_t>> getClassicSniffMinIntervals();

std::vector<std::optional<std::uint32_t>> getClassicSniffAttempts();

std::vector<std::optional<std::uint32_t>> getClassicSniffTimeouts();

std::optional<std::uint32_t> getLeMinConnectionInterval();

std::optional<std::uint32_t> getLeMaxConnectionInterval();

std::optional<std::uint32_t> getLeConnectionLatency();

std::optional<std::uint32_t> getLeConnectionSupervisionTimeout();

std::optional<std::uint32_t> getLeDirectConnectionTimeout();

std::optional<std::uint32_t> getLeConnectionScanIntervalFast();

std::optional<std::uint32_t> getLeConnectionScanWindowFast();

std::optional<std::uint32_t> getLeConnectionScanWindow2mFast();

std::optional<std::uint32_t> getLeConnectionScanWindowCodedFast();

std::optional<std::uint32_t> getLeConnectionScanIntervalSlow();

std::optional<std::uint32_t> getLeConnectionScanWindowSlow();

std::optional<std::uint32_t> getLeInquiryScanInterval();

std::optional<std::uint32_t> getLeInquiryScanWindow();

std::optional<bool> getLeVendorCapabilitiesEnabled();

std::optional<std::uint32_t> getLeMaxNumberOfConcurrentConnections();

std::vector<std::optional<std::string>> dsa_transport_preference();

std::optional<bool> getDisableEnchancedConnection();

std::optional<bool> isScoManagedByAudioEnabled();

}  // namespace android::sysprop::BluetoothProperties
