// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::CrashRecoveryProperties {

std::optional<std::int64_t> lastFactoryResetTimeMs();
bool lastFactoryResetTimeMs(const std::optional<std::int64_t>& value);

std::optional<std::int64_t> rescueBootStart();
bool rescueBootStart(const std::optional<std::int64_t>& value);

std::optional<std::int32_t> rescueBootCount();
bool rescueBootCount(const std::optional<std::int32_t>& value);

std::optional<std::int64_t> bootMitigationStart();
bool bootMitigationStart(const std::optional<std::int64_t>& value);

std::optional<std::int32_t> bootMitigationCount();
bool bootMitigationCount(const std::optional<std::int32_t>& value);

std::optional<bool> attemptingReboot();
bool attemptingReboot(const std::optional<bool>& value);

std::optional<bool> attemptingFactoryReset();
bool attemptingFactoryReset(const std::optional<bool>& value);

std::optional<std::int32_t> maxRescueLevelAttempted();
bool maxRescueLevelAttempted(const std::optional<std::int32_t>& value);

std::optional<bool> enableRescueParty();
bool enableRescueParty(const std::optional<bool>& value);

}  // namespace android::sysprop::CrashRecoveryProperties
