// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::HypervisorProperties {

std::optional<std::string> hypervisor_version();

std::optional<bool> hypervisor_vm_supported();

std::optional<bool> hypervisor_protected_vm_supported();

}  // namespace android::sysprop::HypervisorProperties
