// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::InputProperties {

std::optional<bool> simulate_stylus_with_touch();

std::optional<bool> enable_touchpad_gestures_library();

std::optional<bool> enable_motion_prediction();

std::optional<bool> enable_keyboard_backlight_control();

std::optional<bool> force_enable_stylus_pointer_icon();

std::optional<bool> enable_keyboard_backlight_animation();

std::optional<bool> enable_input_device_usage_metrics();

std::optional<bool> enable_keyboard_backlight_custom_levels();

std::optional<bool> enable_ambient_keyboard_backlight_control();

}  // namespace android::sysprop::InputProperties
