// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::MediaProperties {

std::optional<std::int32_t> swcodec_ion_heapmask();

std::optional<std::int32_t> swcodec_ion_align();

std::optional<std::int32_t> swcodec_ion_flags();

std::optional<std::int32_t> codec2_dmabuf_padding();

std::optional<std::int32_t> resolution_limit_32bit();

enum class codec2_hal_selection_values {
    AIDL,
    HIDL,
};

std::optional<codec2_hal_selection_values> codec2_hal_selection();

}  // namespace android::sysprop::MediaProperties
