// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::MemoryProperties {

std::optional<std::string> memory_ddr_size();

}  // namespace android::sysprop::MemoryProperties
