// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::NfcProperties {

std::optional<bool> debug_enabled();
bool debug_enabled(const std::optional<bool>& value);

enum class snoop_log_mode_values {
    FULL,
    FILTERED,
};

std::optional<snoop_log_mode_values> snoop_log_mode();
bool snoop_log_mode(const std::optional<snoop_log_mode_values>& value);

std::optional<bool> vendor_debug_enabled();
bool vendor_debug_enabled(const std::optional<bool>& value);

std::optional<bool> skipNdefRead();

std::optional<bool> initialized();
bool initialized(const std::optional<bool>& value);

}  // namespace android::sysprop::NfcProperties
