// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::PowerProperties {

std::optional<std::int32_t> fixed_performance_scale_factor();

std::optional<bool> battery_input_suspended();
bool battery_input_suspended(const std::optional<bool>& value);

std::optional<bool> permissionless_turn_screen_on();
bool permissionless_turn_screen_on(const std::optional<bool>& value);

std::optional<bool> waive_target_sdk_check_for_turn_screen_on();

}  // namespace android::sysprop::PowerProperties
