// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::ThreadNetworkProperties {

std::optional<std::string> country_code();

}  // namespace android::sysprop::ThreadNetworkProperties
