// Generated by the sysprop generator. DO NOT EDIT!

#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace android::sysprop::WidevineProperties {

std::optional<bool> forcel3_enabled();
bool forcel3_enabled(const std::optional<bool>& value);

}  // namespace android::sysprop::WidevineProperties
